name: sliding_drawer
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
