name: sliding_drawer
description: sliding_drawer package was created for nice and convenient way to show drawer with sliding animation.
version: 1.0.0

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
